FROM node:20-alpine

WORKDIR /usr/src/app

# Install all deps including devDependencies for nodemon
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

EXPOSE 5000

# Run in dev mode with nodemon
CMD ["npm", "run", "dev"]

